1581. Customer Who Visited but Did Not Make Any Transactions

SELECT V.CUSTOMER_ID, COUNT(CUSTOMER_ID)
AS COUNT_NO_TRANS
FROM VISITS V LEFT JOIN TRANSACTIONS T
ON V.VISIT_ID = T.VISIT_ID
WHERE T.TRANSACTION_ID IS NULL
GROUP BY V.CUSTOMER_ID;